/**
 * Bill of materials, and the validation that keeps it honest.
 *
 * This is the module the user's printer eats. Everything here is pure: it reads
 * a LayoutDoc and a Catalog, and returns new objects. No DOM, no I/O, no clock,
 * no randomness, and nothing passed in is ever mutated.
 *
 * The rules that matter, and why:
 *
 *  R1. Full precision is kept in the accumulators and rounded exactly once, at
 *      the boundary. Totals are summed from unrounded per-unit values, never
 *      from the rounded numbers on the lines — 60 lines each rounded to the
 *      whole minute drift by tens of minutes, which is a wrong BOM that looks
 *      right. Grams -> 1 dp, metres -> 2 dp, minutes -> whole.
 *
 *  R2. A part appears on exactly one line. Inserts and fasteners (catalogue
 *      `type` of 'insert' or 'fastener') go to `Bom.fasteners`, everything else
 *      to `Bom.printed`, whether the quantity came from a direct placement, from
 *      another part's `requires[]`, or from both. Splitting the same STL across
 *      two lines is exactly how someone prints the wrong number of them.
 *
 *  R3. Requirements are expanded one level: a placed part pulls in its
 *      `requires[]`. A required part's own `requires[]` is NOT expanded — no
 *      shipped part nests, and one level makes a requirement cycle structurally
 *      impossible rather than silently truncated. `hardware[]` IS collected from
 *      every part in the BOM, placed or required, so the screws that come with
 *      an insert are counted once per insert.
 *
 *  R4. Nothing throws. A partId missing from the catalogue is reported as an
 *      `unknown-part` issue and contributes nothing; the rest of the BOM is
 *      still computed and still usable.
 *
 *  R5. Output order is deterministic and independent of placement order:
 *      lines by name then partId, shopping by item name, issues grouped by code.
 */

import { customPanelGroups, isCustomPanel } from './customiser';
import { fixingsFor, JUNCTION_FIXING_ID, type FixingPlan } from './fixings';
import { fastenersNeedReview, socketProvidesOf, socketsOf } from './overrides';
import { hexKey, hexSub, keyToHex, placedPanelCells, placeFootprint } from './hex';
import { crossesSeam } from './tiling';
import type {
  Bom,
  BomLine,
  Catalog,
  CatalogPart,
  Hex,
  Issue,
  LayoutDoc,
  PlacedItem,
  PlacedPanel,
} from './types';

// ---------------------------------------------------------------------------
// Small, boring helpers. Defensive because the catalogue is generated JSON:
// a field that is missing on disk must degrade to zero, not to NaN in a total.
// ---------------------------------------------------------------------------

const ORIGIN: Hex = { q: 0, r: 0 };

/** Locale-independent string order, so sorting is identical everywhere. */
const byString = (a: string, b: string): number => (a < b ? -1 : a > b ? 1 : 0);

/** Reading order for reported cells: down the rows, then along a row. */
const byCell = (a: Hex, b: Hex): number => a.r - b.r || a.q - b.q;

function asArray<T>(value: T[] | undefined | null): T[] {
  return Array.isArray(value) ? value : [];
}

function finite(value: number | undefined | null): number {
  return typeof value === 'number' && Number.isFinite(value) ? value : 0;
}

/** A count of physical things: finite and never negative. */
function countOf(value: number | undefined | null): number {
  const n = finite(value);
  return n > 0 ? n : 0;
}

/**
 * Round at the boundary only.
 *
 * The nudge absorbs binary representation error — 0.05 × 40 is 2.0000000000000004
 * and 1.15 × 100 is 114.99999999999999 — so a value that is decimally exact
 * rounds to itself instead of to a neighbour. 1e-9 is far below any real print
 * estimate and far above the representation error at these magnitudes.
 */
function roundTo(value: number, dp: number): number {
  if (!Number.isFinite(value)) return 0;
  const factor = 10 ** dp;
  const scaled = value * factor;
  const rounded = Math.round(scaled + (scaled < 0 ? -1e-9 : 1e-9)) / factor;
  return Object.is(rounded, -0) ? 0 : rounded;
}

const roundMinutes = (v: number): number => roundTo(v, 0);
const roundGrams = (v: number): number => roundTo(v, 1);
const roundMetres = (v: number): number => roundTo(v, 2);

function bump(map: Map<string, number>, key: string, amount: number): void {
  map.set(key, (map.get(key) ?? 0) + amount);
}

// ---------------------------------------------------------------------------
// Catalogue index
// ---------------------------------------------------------------------------

/**
 * partId -> part, memoised per Catalog object so that validating 200 items does
 * not rebuild the index 200 times. The catalogue is read-only by contract (it is
 * generated by tools/scan.py and consumed, never edited), so this is a cache of
 * a pure function, not hidden state. First entry wins on a duplicate id.
 */
const indexCache = new WeakMap<Catalog, ReadonlyMap<string, CatalogPart>>();

function partIndex(catalog: Catalog): ReadonlyMap<string, CatalogPart> {
  const cached = indexCache.get(catalog);
  if (cached !== undefined) return cached;

  const map = new Map<string, CatalogPart>();
  for (const part of asArray(catalog?.parts)) {
    if (part && typeof part.id === 'string' && !map.has(part.id)) map.set(part.id, part);
  }
  indexCache.set(catalog, map);
  return map;
}

const isFastener = (part: CatalogPart): boolean =>
  part.type === 'insert' || part.type === 'fastener';

function estimateOf(part: CatalogPart): {
  minutes: number;
  grams: number;
  metres: number;
  supports: boolean;
} {
  const print = part.print;
  return {
    minutes: finite(print?.minutes),
    grams: finite(print?.grams),
    metres: finite(print?.metres),
    supports: print?.supports === true,
  };
}

/**
 * Is this part's footprint a bound rather than a measurement?
 *
 * `needsReview` is written by `tools/scan.py` and by the browser importer, but
 * it is not part of the `CatalogPart` contract, so it is read structurally and
 * anything other than an explicit `true` counts as measured.
 */
const needsReviewOf = (part: CatalogPart): boolean =>
  (part as unknown as { needsReview?: unknown }).needsReview === true;

/** Modelled print figures rather than a real slice. */
const isEstimated = (part: CatalogPart): boolean => part.print?.source === 'volume';

/**
 * Does this part take a screw into the WALL, as opposed to a bolt into another
 * printed part? Read from the hardware it asks for, not from its name.
 */
const isWallMount = (part: CatalogPart): boolean =>
  asArray(part.hardware).some((h) => /wall (screw|plug)/i.test(h?.item ?? ''));

/**
 * The catalogue's wall-mount fastener: the lightest one-cell insert that takes
 * a wall screw.
 *
 * The type check is load-bearing, not defensive. A PANEL may legitimately carry
 * `Wall plug` in its own hardware — that is the fallback `tools/scan.py` writes
 * when the catalogue has no countersunk insert to require — and without this,
 * the fixing plan picked the panel as its own fastener and multiplied the
 * panel's hardware by the fixing count. A test fixture caught it; a real
 * catalogue would have too, one panel at a time.
 */
function wallMountPart(index: ReadonlyMap<string, CatalogPart>): CatalogPart | undefined {
  let best: CatalogPart | undefined;
  for (const part of index.values()) {
    if (part.type !== 'insert' && part.type !== 'fastener') continue;
    if (!isWallMount(part)) continue;
    // One cell each, so the plan's cell count and the order agree. A two-cell
    // wall fastener would need the plan to reserve two cells per fixing.
    if (asArray(part.footprint).length > 1) continue;
    if (best === undefined || finite(part.print?.grams) < finite(best.print?.grams)) best = part;
  }
  return best;
}

// ---------------------------------------------------------------------------
// Footprints
// ---------------------------------------------------------------------------

function dedupeCells(cells: Hex[]): Hex[] {
  const seen = new Set<string>();
  const out: Hex[] = [];
  for (const c of cells) {
    const key = hexKey(c);
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(c);
  }
  return out;
}

/**
 * An EMPTY insert: one that is nothing but a socket.
 *
 * Derived, not listed: an insert or fastener that asks for no hardware takes no
 * bolt and no wall screw, so all it offers is the hexagonal socket a peg plugs
 * into. That is `insert-empty` and the whole hollow family, and it excludes
 * every M3/M4/M5 insert and every countersunk one — which is what "an empty
 * insert of any kind" means.
 */
export function isEmptyInsert(part: CatalogPart | undefined): boolean {
  if (part === undefined) return false;
  if (part.type !== 'insert' && part.type !== 'fastener') return false;
  return asArray(part.hardware).length === 0;
}

/** Does this part hang on a plain socket, rather than on a bolt or a screw? */
function mountsThroughSocket(
  part: CatalogPart | undefined,
  index: ReadonlyMap<string, CatalogPart>,
): boolean {
  return asArray(part?.requires).some((r) => r && isEmptyInsert(index.get(r.partId)));
}

/**
 * The fixing plan for a document, with the ONE reading of "occupied" that the
 * parts list and the 3D view must share.
 *
 * Two sets, because a cell can be busy in two different ways. Anything on a
 * cell keeps the spacing grid out of it — a wall screw needs a hole and a
 * screwdriver needs to reach it. But a part that mounts through a plain socket
 * sitting on a JUNCTION's socket cell is not in the way of anything: that
 * socket is what it is pegged into. Treating those the same made the wall mount
 * disappear the moment you hung a hook on one of its open holes (D48).
 */
export function fixingPlanFor(
  doc: LayoutDoc | undefined,
  catalog: Catalog,
  spacingMm?: number,
): FixingPlan {
  const index = partIndex(catalog);
  const avoid = new Set<string>();
  const shared = new Set<string>();
  for (const item of asArray(doc?.items)) {
    const part = index.get(item.partId);
    const pegged = mountsThroughSocket(part, index);
    for (const cell of itemCells(item, catalog)) {
      const key = hexKey(cell);
      avoid.add(key);
      if (pegged) shared.add(key);
    }
  }
  const junction = index.get(JUNCTION_FIXING_ID);
  const anchor = junction?.anchor ?? ORIGIN;
  const junctionSockets = socketsOf(junction).map((c) => hexSub(c, anchor));
  return fixingsFor(doc as LayoutDoc, spacingMm, avoid, { cells: shared, junctionSockets });
}

/**
 * The cells a placed item actually covers on the wall.
 *
 * The footprint is stored as offsets from the part's anchor and normally has the
 * anchor at {0,0} (hex.ts rotates about the origin for exactly that reason). A
 * catalogue that nevertheless names a non-zero anchor is honoured by shifting the
 * footprint first, so the anchor is what lands on `item.at` and what the shape
 * rotates about either way.
 *
 * An unknown partId has no known footprint, so it covers nothing: it cannot be
 * off-panel and it cannot overlap. The missing part is reported once, by
 * `validate`, rather than as a cascade of geometry errors.
 */
export function itemCells(item: PlacedItem, catalog: Catalog): Hex[] {
  const part = partIndex(catalog).get(item.partId);
  if (part === undefined) return [];

  const footprint = asArray(part.footprint);
  const cells = footprint.length > 0 ? footprint : [ORIGIN];
  const anchor = part.anchor ?? ORIGIN;
  const local =
    anchor.q === 0 && anchor.r === 0 ? cells : cells.map((c) => hexSub(c, anchor));

  return dedupeCells(placeFootprint(local, item.at ?? ORIGIN, item.rotation));
}

/**
 * The cells of a placed item that something can be installed INTO — its
 * mounting positions, on the wall rather than in the part's own frame.
 *
 * Exactly `itemCells`'s transform applied to a different list, and deliberately
 * written as the same three steps: the anchor shift, the placement, the dedupe.
 * A socket that landed one cell from the part it belongs to would let an insert
 * be installed into solid material, and the two lists disagreeing is precisely
 * how `partCells` and `itemCells` once came apart.
 */
export function itemSocketCells(item: PlacedItem, catalog: Catalog): Hex[] {
  const part = partIndex(catalog).get(item.partId);
  if (part === undefined) return [];
  const sockets = socketsOf(part);
  if (sockets.length === 0) return [];

  const anchor = part.anchor ?? ORIGIN;
  const local =
    anchor.q === 0 && anchor.r === 0 ? sockets : sockets.map((c) => hexSub(c, anchor));

  return dedupeCells(placeFootprint(local, item.at ?? ORIGIN, item.rotation));
}

/** The cells a placed panel covers. The document's own columns/rows are authoritative. */
function panelCellsOf(panel: PlacedPanel): Hex[] {
  return placedPanelCells({
    origin: panel.origin ?? ORIGIN,
    columns: Math.floor(countOf(panel.columns)),
    rows: Math.floor(countOf(panel.rows)),
    omit: panel.omit,
  });
}

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------

interface Collision {
  a: string;
  b: string;
  cells: Hex[];
}

/** Every pair of ids that share at least one cell, with the cells they share. */
function collisions(occupants: Map<string, string[]>): Collision[] {
  const pairs = new Map<string, Map<string, Hex[]>>();

  for (const [key, ids] of occupants) {
    if (ids.length < 2) continue;
    const unique = [...new Set(ids)].sort(byString);
    for (let i = 0; i < unique.length; i++) {
      for (let j = i + 1; j < unique.length; j++) {
        const a = unique[i]!;
        const b = unique[j]!;
        let inner = pairs.get(a);
        if (inner === undefined) {
          inner = new Map<string, Hex[]>();
          pairs.set(a, inner);
        }
        const cells = inner.get(b);
        if (cells === undefined) inner.set(b, [keyToHex(key)]);
        else cells.push(keyToHex(key));
      }
    }
  }

  const out: Collision[] = [];
  for (const [a, inner] of pairs) {
    for (const [b, cells] of inner) out.push({ a, b, cells: cells.sort(byCell) });
  }
  return out.sort((x, y) => byString(x.a, y.a) || byString(x.b, y.b));
}

function occupancyOf(entries: { id: string; cells: Hex[] }[]): Map<string, string[]> {
  const occupants = new Map<string, string[]>();
  for (const entry of entries) {
    for (const cell of entry.cells) {
      const key = hexKey(cell);
      const ids = occupants.get(key);
      if (ids === undefined) occupants.set(key, [entry.id]);
      else ids.push(entry.id);
    }
  }
  return occupants;
}

/**
 * Everything wrong with the layout that this module can see.
 *
 * Seam detection itself belongs to the tiling module; this function calls it
 * rather than reimplementing it, so the warning a file raises on load and the
 * warning a drop raises in the editor are the same test.
 */
export function validate(doc: LayoutDoc, catalog: Catalog): Issue[] {
  const index = partIndex(catalog);
  const panels = asArray(doc?.panels);
  const items = asArray(doc?.items);
  const issues: Issue[] = [];

  // --- unknown-part -------------------------------------------------------
  // One issue per missing partId, listing every placement that wants it. Forty
  // copies of the same missing shelf is one problem, not forty.
  const unknown = new Map<string, Set<string>>();
  const noteUnknown = (partId: string, byId: string): void => {
    const label = typeof partId === 'string' ? partId : String(partId);
    const ids = unknown.get(label);
    if (ids === undefined) unknown.set(label, new Set([byId]));
    else ids.add(byId);
  };
  const scanRefs = (id: string, partId: string): void => {
    const part = index.get(partId);
    if (part === undefined) {
      noteUnknown(partId, id);
      return;
    }
    for (const req of asArray(part.requires)) {
      if (req && !index.has(req.partId)) noteUnknown(req.partId, id);
    }
  };
  for (const panel of panels) scanRefs(panel.id, panel.partId);
  for (const item of items) scanRefs(item.id, item.partId);

  for (const partId of [...unknown.keys()].sort(byString)) {
    const ids = [...(unknown.get(partId) ?? [])].sort(byString);
    issues.push({
      level: 'error',
      code: 'unknown-part',
      message: `Part "${partId}" is not in the catalogue (referenced by ${ids.length} placement${
        ids.length === 1 ? '' : 's'
      }). It contributes nothing to the BOM.`,
      itemIds: ids,
    });
  }

  // --- panel-overlap ------------------------------------------------------
  const panelFootprints = panels.map((panel) => ({ id: panel.id, cells: panelCellsOf(panel) }));
  for (const clash of collisions(occupancyOf(panelFootprints))) {
    issues.push({
      level: 'error',
      code: 'panel-overlap',
      message: `Panels "${clash.a}" and "${clash.b}" overlap on ${clash.cells.length} cell${
        clash.cells.length === 1 ? '' : 's'
      }.`,
      itemIds: [clash.a, clash.b],
      cells: clash.cells,
    });
  }

  // --- overlap ------------------------------------------------------------
  const itemFootprints = items.map((item) => ({ id: item.id, cells: itemCells(item, catalog) }));

  // Sharing a cell is only an ERROR when both things plug INTO it — there is
  // one hexagonal hole and one insert can sit in it. Accessories bolt onto an
  // insert and stand proud of the panel, and mounting things on top of one
  // another is what the system is for, so those overlaps are advisory.
  const itemsById = new Map(items.map((i) => [i.id, i]));
  const plugsIn = (itemId: string): boolean => {
    const it = itemsById.get(itemId);
    const p = it ? catalog.parts.find((x) => x.id === it.partId) : undefined;
    return p !== undefined && (p.type === 'insert' || p.type === 'fastener');
  };

  /**
   * Cells one item OFFERS to another: its sockets, on the wall.
   *
   * The store lets a part be installed into one of these, so the validator has
   * to know about them too — otherwise the app accepts a drop and the parts list
   * immediately calls it an error, which is the exact split `partCells` and
   * `itemCells` were unified to prevent. It surfaced within a minute of the
   * store learning the rule: a junction insert, an insert dropped into one of
   * its three sockets, and a red panel saying only one part can occupy a cell.
   */
  const socketsById = new Map(items.map((i) => [i.id, itemSocketCells(i, catalog).map(hexKey)]));
  const hosts = (itemId: string, cells: readonly Hex[]): boolean => {
    const offered = socketsById.get(itemId);
    if (offered === undefined || offered.length === 0) return false;
    return cells.every((c) => offered.includes(hexKey(c)));
  };

  for (const clash of collisions(occupancyOf(itemFootprints))) {
    // Only the impossible case is reported. Two accessories sharing cells is
    // ordinary — they bolt on at different depths — and reporting it would put
    // a warning on the parts list for a layout that is perfectly fine.
    if (!plugsIn(clash.a) || !plugsIn(clash.b)) continue;
    // ...and neither is one thing installed INTO another's socket, which is a
    // mounting position doing its job.
    if (hosts(clash.a, clash.cells) || hosts(clash.b, clash.cells)) continue;
    const n = clash.cells.length;
    issues.push({
      level: 'error',
      code: 'overlap',
      message:
        `Two inserts share the same hole: "${clash.a}" and "${clash.b}" ` +
        `on ${n} cell${n === 1 ? '' : 's'}.`,
      itemIds: [clash.a, clash.b],
      cells: clash.cells,
    });
  }

  // --- off-panel ----------------------------------------------------------
  // Only meaningful once there is a panel: with none, every item is trivially
  // off-panel, and the one no-panel warning below says it better than N errors.
  if (panels.length > 0) {
    const covered = new Set<string>();
    for (const panel of panelFootprints) for (const cell of panel.cells) covered.add(hexKey(cell));

    for (const footprint of itemFootprints) {
      const outside = footprint.cells.filter((c) => !covered.has(hexKey(c))).sort(byCell);
      if (outside.length === 0) continue;
      issues.push({
        level: 'error',
        code: 'off-panel',
        message: `Item "${footprint.id}" sits on ${outside.length} cell${
          outside.length === 1 ? '' : 's'
        } that no panel covers.`,
        itemIds: [footprint.id],
        cells: outside,
      });
    }
  }

  // --- crosses-seam -------------------------------------------------------
  // The editor warns about this at drop time, which covers a layout you built
  // by hand and nothing else: a layout that arrived by file, by share link, or
  // by a wall resize that moved the panels under it was never advised at all.
  // Spanning a seam is legal — some inserts exist to do it — so it stays a
  // warning, one per item.
  if (panels.length > 1) {
    for (const footprint of itemFootprints) {
      if (footprint.cells.length < 2) continue;
      if (!crossesSeam(footprint.cells, panels)) continue;
      issues.push({
        level: 'warning',
        code: 'crosses-seam',
        message: `Item "${footprint.id}" spans the join between two panels.`,
        itemIds: [footprint.id],
        cells: [...footprint.cells].sort(byCell),
      });
    }
  }

  // --- no-panel -----------------------------------------------------------
  if (panels.length === 0 && items.length > 0) {
    issues.push({
      level: 'warning',
      code: 'no-panel',
      message: `The layout has ${items.length} item${
        items.length === 1 ? '' : 's'
      } but no panels to mount them on.`,
      itemIds: items.map((item) => item.id).sort(byString),
    });
  }

  // --- no-room-for-mounts -------------------------------------------------
  // A panel hangs on the wall through its own cells: a countersunk insert drops
  // into one and takes a wall screw. Fill every cell with accessories and there
  // is nowhere left to put one — a parts list that is correct about what to
  // print and silent about what cannot be built.
  //
  // The fixing planner routes around occupied cells, so the only panels left
  // are the ones with NO free cell at all. That is a much sharper warning than
  // the old free-cells-versus-a-quota arithmetic, and it comes from the same
  // plan that ordered the fixings, so the two cannot drift apart.
  const taken = new Set<string>();
  for (const footprint of itemFootprints) {
    for (const cell of footprint.cells) taken.add(hexKey(cell));
  }
  for (const panelId of fixingPlanFor(doc, catalog).starvedPanelIds) {
    issues.push({
      level: 'warning',
      code: 'no-room-for-mounts',
      message:
        `Panel "${panelId}" has no free cell left for the fixing that holds it to the ` +
        `wall — accessories occupy all of them. Clear one cell, or fit its fixing first.`,
      itemIds: [panelId],
    });
  }

  return issues;
}

// ---------------------------------------------------------------------------
// BOM
// ---------------------------------------------------------------------------

/**
 * The print list.
 *
 * Always returns a usable BOM: issues are reported alongside, and anything the
 * catalogue cannot explain is left out of the numbers rather than guessed at or
 * thrown over.
 */
export function computeBom(doc: LayoutDoc, catalog: Catalog): Bom {
  const index = partIndex(catalog);
  const issues = validate(doc, catalog);

  // How many times each partId was placed on the wall (panels and items alike).
  const placements = new Map<string, number>();
  const asPanel = new Map<string, number>();
  for (const panel of asArray(doc?.panels)) {
    // A panel cut round a light switch is NOT the stock plate any more, and
    // counting it as one would have you print 50 copies of a file when four of
    // them will not fit. Custom panels are reported on their own lines below.
    if (isCustomPanel(panel)) continue;
    bump(placements, panel.partId, 1);
    bump(asPanel, panel.partId, 1);
  }
  for (const item of asArray(doc?.items)) bump(placements, item.partId, 1);

  // partId -> total physical count, placements plus rolled-up requirements.
  const quantities = new Map<string, number>();
  for (const [partId, times] of placements) {
    if (index.has(partId)) bump(quantities, partId, times);
  }

  /**
   * Wall fixings are a property of the ASSEMBLY, not of one plate.
   *
   * `tools/scan.py` writes `requires: insert-countersunk × (4 + cells/50)` onto
   * every panel part, and multiplying that by the number of plates gave 370
   * wall screws for a 2400 × 1200 wall — one every 88 mm. The panels interlock
   * and multi-cell inserts bridge the seams, so the sheet takes fixings at a
   * spacing, and `fixings.ts` decides where. A panel's own requirement for a
   * wall-mount fastener is therefore superseded here rather than expanded.
   *
   * Superseded only for panels placed AS PANELS. A panel part dropped as a
   * loose item is not part of the assembly the plan covers, so it keeps its own
   * declared requirement — otherwise its fixings would vanish entirely.
   *
   * A rescan will stop emitting the per-panel requirement (see the note in
   * tools/scan.py), at which point this becomes a no-op rather than a
   * correction.
   */
  const fixings = fixingPlanFor(doc, catalog);
  const isWallMountOf = (requiredId: string): boolean => {
    const required = index.get(requiredId);
    return (
      required !== undefined &&
      (required.type === 'fastener' || required.type === 'insert') &&
      isWallMount(required)
    );
  };

  /*
   * INSERTS THE WALL ALREADY HAS.
   *
   * The combined wall fastener is one screw hole and three open sockets, and
   * those sockets are inserts: an accessory hung on one of them does not also
   * need an `insert-empty` printed for it. Ordering both is the same
   * double-count as a fixing being claimed twice — you end up printing a part
   * that is already in the wall.
   *
   * Only where somebody has SAID the socket does that job (`socketProvides`).
   * Two sockets being the same size is not proof they are interchangeable, and
   * this is a shopping list.
   *
   * Sockets come from placed items and from the junction fixings the plan puts
   * in at the seams — those are in the wall whether or not anybody dropped them
   * by hand. Each is consumed at most once, in document order, so two
   * accessories over the same socket cannot both claim it.
   */
  const socketAt = new Map<string, { provides: string; by: string }>();
  const noteSocket = (item: PlacedItem, provides: string): void => {
    for (const cell of itemSocketCells(item, catalog)) {
      const key = hexKey(cell);
      if (!socketAt.has(key)) socketAt.set(key, { provides, by: item.id });
    }
  };
  for (const item of asArray(doc?.items)) {
    const provides = socketProvidesOf(index.get(item.partId));
    if (provides !== undefined) noteSocket(item, provides);
  }
  const junctionPart = index.get(JUNCTION_FIXING_ID);
  const junctionProvides = socketProvidesOf(junctionPart);
  if (junctionPart !== undefined && junctionProvides !== undefined) {
    for (const [n, junction] of fixings.junctions.entries()) {
      // Through `itemSocketCells`, so a planned fixing and a placed one place
      // their sockets by the same transform.
      noteSocket(
        {
          id: `fixing/${n}`,
          partId: JUNCTION_FIXING_ID,
          at: junction.anchor,
          rotation: junction.rotation,
        },
        junctionProvides,
      );
    }
  }

  /**
   * Does a socket that provides `has` satisfy a part that asks for `wants`?
   *
   * The same id, obviously. And any EMPTY insert answers any other: they are
   * all just a hexagonal socket for a peg, so a part that asks for
   * `insert-empty` is as well served by the hollow family's socket as by its
   * own — which is what "an empty insert of any kind" means, and what a person
   * choosing a fastener in the inspector expects when they then hang the part
   * on a wall fastener's open hole.
   *
   * It is NOT symmetric with the bolted ones: an M3 bore answers only a part
   * that wants an M3 insert. A plain socket has no thread, and a part that
   * needs one still needs it.
   */
  const answers = (has: string, wants: string): boolean =>
    has === wants || (isEmptyInsert(index.get(has)) && isEmptyInsert(index.get(wants)));

  /** partId -> requiredId -> how many the wall already provides. */
  const provided = new Map<string, Map<string, number>>();
  const spent = new Set<string>();
  for (const item of asArray(doc?.items)) {
    const part = index.get(item.partId);
    if (part === undefined) continue;
    const wants = asArray(part.requires);
    if (wants.length === 0) continue;
    const cells = itemCells(item, catalog);
    for (const req of wants) {
      if (!req || !index.has(req.partId)) continue;
      let left = countOf(req.count);
      for (const cell of cells) {
        if (left <= 0) break;
        const key = hexKey(cell);
        const socket = socketAt.get(key);
        // Never its own socket, and never one already claimed.
        if (socket === undefined || socket.by === item.id || spent.has(key)) continue;
        if (!answers(socket.provides, req.partId)) continue;
        spent.add(key);
        left -= 1;
        const forPart = provided.get(item.partId) ?? new Map<string, number>();
        forPart.set(req.partId, (forPart.get(req.partId) ?? 0) + 1);
        provided.set(item.partId, forPart);
      }
    }
  }
  /** How many of each insert the wall provided, for the lines to say so. */
  const providedTotals = new Map<string, number>();

  for (const [partId, times] of placements) {
    const part = index.get(partId);
    if (part === undefined) continue;
    // Placements of this part that the fixing plan already covers.
    const covered = part.type === 'panel' ? countOf(asPanel.get(partId)) : 0;
    const expand = times - covered;
    for (const req of asArray(part.requires)) {
      if (!req || !index.has(req.partId)) continue;
      const uses = isWallMountOf(req.partId) ? expand : times;
      const already = provided.get(partId)?.get(req.partId) ?? 0;
      const needed = countOf(req.count) * uses - already;
      if (already > 0) {
        providedTotals.set(req.partId, (providedTotals.get(req.partId) ?? 0) + already);
      }
      if (needed > 0) bump(quantities, req.partId, needed);
    }
  }

  // ...and the plan's own fixings go in once, for the whole wall.
  if (fixings.cells.length > 0) {
    const mount = wallMountPart(index);
    if (mount !== undefined) bump(quantities, mount.id, fixings.cells.length);
  }
  /**
   * Junctions get the four-cell countersunk insert, not four single-cell ones.
   *
   * HSW-SPEC §4: the panels have no screw holes of their own, and a multi-cell
   * insert straddling the join is what holds them to each other as well as to
   * the wall. Four separate fixings, one per plate, fix each plate and leave
   * the join itself unsupported.
   */
  if (fixings.junctions.length > 0 && index.has(JUNCTION_FIXING_ID)) {
    bump(quantities, JUNCTION_FIXING_ID, fixings.junctions.length);
  }

  // Bought hardware, from every part in the BOM — including the inserts that
  // only got there via someone else's requires[].
  const shoppingTotals = new Map<string, number>();
  for (const [partId, quantity] of quantities) {
    const part = index.get(partId);
    if (part === undefined) continue;
    for (const hw of asArray(part.hardware)) {
      if (!hw || typeof hw.item !== 'string' || hw.item.length === 0) continue;
      const needed = countOf(hw.count) * quantity;
      if (needed > 0) bump(shoppingTotals, hw.item, needed);
    }
  }

  // Lines. Unrounded running totals; rounding happens once, below.
  const printed: BomLine[] = [];
  const fasteners: BomLine[] = [];
  let totalParts = 0;
  let totalMinutes = 0;
  let totalGrams = 0;
  let totalMetres = 0;

  for (const [partId, quantity] of quantities) {
    const part = index.get(partId);
    if (part === undefined || quantity <= 0) continue;
    const est = estimateOf(part);

    totalParts += quantity;
    totalMinutes += est.minutes * quantity;
    totalGrams += est.grams * quantity;
    totalMetres += est.metres * quantity;

    const line: BomLine = {
      partId,
      name: part.name ?? partId,
      file: part.file ?? '',
      type: part.type ?? 'unknown',
      quantity,
      minutes: roundMinutes(est.minutes * quantity),
      grams: roundGrams(est.grams * quantity),
      metres: roundMetres(est.metres * quantity),
      // Per-unit figures come from the catalogue, never from total ÷ quantity:
      // that division reads back a number that has already been rounded.
      minutesEach: roundTo(est.minutes, 2),
      gramsEach: roundGrams(est.grams),
      metresEach: roundMetres(est.metres),
      supports: est.supports,
      needsReview: needsReviewOf(part),
      estimated: isEstimated(part),
      fastenersUnknown: fastenersNeedReview(part),
      providedBySockets: providedTotals.get(partId) ?? 0,
    };
    (isFastener(part) ? fasteners : printed).push(line);
  }

  /**
   * Custom panels: the same block with cells cut out, generated rather than
   * printed from a shipped STL.
   *
   * The print estimate is the stock plate's, scaled by the fraction of cells
   * that survive. That is a model, not a slice — a hole removes plate as well as
   * a bore, so the true saving is slightly larger — and it is marked estimated
   * like every other modelled figure.
   */
  for (const [index_, group] of customPanelGroups(asArray(doc?.panels)).entries()) {
    const first = group.panels[0]!;
    const stock = index.get(first.partId);
    const stockCells = Math.max(1, asArray(stock?.footprint).length);
    const kept = group.params?.cellCount ?? stockCells;
    const share = Math.min(1, kept / stockCells);
    const est = stock ? estimateOf(stock) : { minutes: 0, grams: 0, metres: 0, supports: false };
    const quantity = group.panels.length;
    const label = `Custom panel ${String.fromCharCode(65 + index_)}`;

    totalParts += quantity;
    totalMinutes += est.minutes * share * quantity;
    totalGrams += est.grams * share * quantity;
    totalMetres += est.metres * share * quantity;

    printed.push({
      partId: `custom/${group.key}`,
      name: `${label} — ${kept} cells, cut round an obstacle`,
      file: '',
      type: 'panel',
      quantity,
      minutes: roundMinutes(est.minutes * share * quantity),
      grams: roundGrams(est.grams * share * quantity),
      metres: roundMetres(est.metres * share * quantity),
      minutesEach: roundTo(est.minutes * share, 2),
      gramsEach: roundGrams(est.grams * share),
      metresEach: roundMetres(est.metres * share),
      supports: est.supports,
      needsReview: false,
      estimated: true,
      fastenersUnknown: false,
      providedBySockets: 0,
    });
  }

  const byNameThenId = (a: BomLine, b: BomLine): number =>
    byString(a.name, b.name) || byString(a.partId, b.partId);
  printed.sort(byNameThenId);
  fasteners.sort(byNameThenId);

  const shopping = [...shoppingTotals.entries()]
    .map(([item, count]) => ({ item, count }))
    .sort((a, b) => byString(a.item, b.item));

  return {
    printed,
    fasteners,
    shopping,
    totals: {
      parts: totalParts,
      minutes: roundMinutes(totalMinutes),
      grams: roundGrams(totalGrams),
      metres: roundMetres(totalMetres),
      distinctParts: printed.length + fasteners.length,
    },
    fixings: {
      count: fixings.cells.length + fixings.junctions.length,
      junctions: fixings.junctions.length,
      spacingMm: fixings.spacingMm,
      perSquareMetre: roundTo(fixings.perSquareMetre, 1),
      starvedPanelIds: fixings.starvedPanelIds,
    },
    issues,
  };
}
