/**
 * Bill of materials, and the validation that keeps it honest.
 *
 * This is the module the user's printer eats. Everything here is pure: it reads
 * a LayoutDoc and a Catalog, and returns new objects. No DOM, no I/O, no clock,
 * no randomness, and nothing passed in is ever mutated.
 *
 * The rules that matter, and why:
 *
 *  R1. Full precision is kept in the accumulators and rounded exactly once, at
 *      the boundary. Totals are summed from unrounded per-unit values, never
 *      from the rounded numbers on the lines — 60 lines each rounded to the
 *      whole minute drift by tens of minutes, which is a wrong BOM that looks
 *      right. Grams -> 1 dp, metres -> 2 dp, minutes -> whole.
 *
 *  R2. A part appears on exactly one line. Inserts and fasteners (catalogue
 *      `type` of 'insert' or 'fastener') go to `Bom.fasteners`, everything else
 *      to `Bom.printed`, whether the quantity came from a direct placement, from
 *      another part's `requires[]`, or from both. Splitting the same STL across
 *      two lines is exactly how someone prints the wrong number of them.
 *
 *  R3. Requirements are expanded one level: a placed part pulls in its
 *      `requires[]`. A required part's own `requires[]` is NOT expanded — no
 *      shipped part nests, and one level makes a requirement cycle structurally
 *      impossible rather than silently truncated. `hardware[]` IS collected from
 *      every part in the BOM, placed or required, so the screws that come with
 *      an insert are counted once per insert.
 *
 *  R4. Nothing throws. A partId missing from the catalogue is reported as an
 *      `unknown-part` issue and contributes nothing; the rest of the BOM is
 *      still computed and still usable.
 *
 *  R5. Output order is deterministic and independent of placement order:
 *      lines by name then partId, shopping by item name, issues grouped by code.
 */

import { hexKey, hexSub, keyToHex, panelCells, placeFootprint } from './hex';
import { crossesSeam } from './tiling';
import type {
  Bom,
  BomLine,
  Catalog,
  CatalogPart,
  Hex,
  Issue,
  LayoutDoc,
  PlacedItem,
  PlacedPanel,
} from './types';

// ---------------------------------------------------------------------------
// Small, boring helpers. Defensive because the catalogue is generated JSON:
// a field that is missing on disk must degrade to zero, not to NaN in a total.
// ---------------------------------------------------------------------------

const ORIGIN: Hex = { q: 0, r: 0 };

/** Locale-independent string order, so sorting is identical everywhere. */
const byString = (a: string, b: string): number => (a < b ? -1 : a > b ? 1 : 0);

/** Reading order for reported cells: down the rows, then along a row. */
const byCell = (a: Hex, b: Hex): number => a.r - b.r || a.q - b.q;

function asArray<T>(value: T[] | undefined | null): T[] {
  return Array.isArray(value) ? value : [];
}

function finite(value: number | undefined | null): number {
  return typeof value === 'number' && Number.isFinite(value) ? value : 0;
}

/** A count of physical things: finite and never negative. */
function countOf(value: number | undefined | null): number {
  const n = finite(value);
  return n > 0 ? n : 0;
}

/**
 * Round at the boundary only.
 *
 * The nudge absorbs binary representation error — 0.05 × 40 is 2.0000000000000004
 * and 1.15 × 100 is 114.99999999999999 — so a value that is decimally exact
 * rounds to itself instead of to a neighbour. 1e-9 is far below any real print
 * estimate and far above the representation error at these magnitudes.
 */
function roundTo(value: number, dp: number): number {
  if (!Number.isFinite(value)) return 0;
  const factor = 10 ** dp;
  const scaled = value * factor;
  const rounded = Math.round(scaled + (scaled < 0 ? -1e-9 : 1e-9)) / factor;
  return Object.is(rounded, -0) ? 0 : rounded;
}

const roundMinutes = (v: number): number => roundTo(v, 0);
const roundGrams = (v: number): number => roundTo(v, 1);
const roundMetres = (v: number): number => roundTo(v, 2);

function bump(map: Map<string, number>, key: string, amount: number): void {
  map.set(key, (map.get(key) ?? 0) + amount);
}

// ---------------------------------------------------------------------------
// Catalogue index
// ---------------------------------------------------------------------------

/**
 * partId -> part, memoised per Catalog object so that validating 200 items does
 * not rebuild the index 200 times. The catalogue is read-only by contract (it is
 * generated by tools/scan.py and consumed, never edited), so this is a cache of
 * a pure function, not hidden state. First entry wins on a duplicate id.
 */
const indexCache = new WeakMap<Catalog, ReadonlyMap<string, CatalogPart>>();

function partIndex(catalog: Catalog): ReadonlyMap<string, CatalogPart> {
  const cached = indexCache.get(catalog);
  if (cached !== undefined) return cached;

  const map = new Map<string, CatalogPart>();
  for (const part of asArray(catalog?.parts)) {
    if (part && typeof part.id === 'string' && !map.has(part.id)) map.set(part.id, part);
  }
  indexCache.set(catalog, map);
  return map;
}

const isFastener = (part: CatalogPart): boolean =>
  part.type === 'insert' || part.type === 'fastener';

function estimateOf(part: CatalogPart): {
  minutes: number;
  grams: number;
  metres: number;
  supports: boolean;
} {
  const print = part.print;
  return {
    minutes: finite(print?.minutes),
    grams: finite(print?.grams),
    metres: finite(print?.metres),
    supports: print?.supports === true,
  };
}

/**
 * Is this part's footprint a bound rather than a measurement?
 *
 * `needsReview` is written by `tools/scan.py` and by the browser importer, but
 * it is not part of the `CatalogPart` contract, so it is read structurally and
 * anything other than an explicit `true` counts as measured.
 */
const needsReviewOf = (part: CatalogPart): boolean =>
  (part as unknown as { needsReview?: unknown }).needsReview === true;

/** Modelled print figures rather than a real slice. */
const isEstimated = (part: CatalogPart): boolean => part.print?.source === 'volume';

// ---------------------------------------------------------------------------
// Footprints
// ---------------------------------------------------------------------------

function dedupeCells(cells: Hex[]): Hex[] {
  const seen = new Set<string>();
  const out: Hex[] = [];
  for (const c of cells) {
    const key = hexKey(c);
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(c);
  }
  return out;
}

/**
 * The cells a placed item actually covers on the wall.
 *
 * The footprint is stored as offsets from the part's anchor and normally has the
 * anchor at {0,0} (hex.ts rotates about the origin for exactly that reason). A
 * catalogue that nevertheless names a non-zero anchor is honoured by shifting the
 * footprint first, so the anchor is what lands on `item.at` and what the shape
 * rotates about either way.
 *
 * An unknown partId has no known footprint, so it covers nothing: it cannot be
 * off-panel and it cannot overlap. The missing part is reported once, by
 * `validate`, rather than as a cascade of geometry errors.
 */
export function itemCells(item: PlacedItem, catalog: Catalog): Hex[] {
  const part = partIndex(catalog).get(item.partId);
  if (part === undefined) return [];

  const footprint = asArray(part.footprint);
  const cells = footprint.length > 0 ? footprint : [ORIGIN];
  const anchor = part.anchor ?? ORIGIN;
  const local =
    anchor.q === 0 && anchor.r === 0 ? cells : cells.map((c) => hexSub(c, anchor));

  return dedupeCells(placeFootprint(local, item.at ?? ORIGIN, item.rotation));
}

/** The cells a placed panel covers. The document's own columns/rows are authoritative. */
function panelCellsOf(panel: PlacedPanel): Hex[] {
  const columns = Math.floor(countOf(panel.columns));
  const rows = Math.floor(countOf(panel.rows));
  return panelCells(panel.origin ?? ORIGIN, columns, rows);
}

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------

interface Collision {
  a: string;
  b: string;
  cells: Hex[];
}

/** Every pair of ids that share at least one cell, with the cells they share. */
function collisions(occupants: Map<string, string[]>): Collision[] {
  const pairs = new Map<string, Map<string, Hex[]>>();

  for (const [key, ids] of occupants) {
    if (ids.length < 2) continue;
    const unique = [...new Set(ids)].sort(byString);
    for (let i = 0; i < unique.length; i++) {
      for (let j = i + 1; j < unique.length; j++) {
        const a = unique[i]!;
        const b = unique[j]!;
        let inner = pairs.get(a);
        if (inner === undefined) {
          inner = new Map<string, Hex[]>();
          pairs.set(a, inner);
        }
        const cells = inner.get(b);
        if (cells === undefined) inner.set(b, [keyToHex(key)]);
        else cells.push(keyToHex(key));
      }
    }
  }

  const out: Collision[] = [];
  for (const [a, inner] of pairs) {
    for (const [b, cells] of inner) out.push({ a, b, cells: cells.sort(byCell) });
  }
  return out.sort((x, y) => byString(x.a, y.a) || byString(x.b, y.b));
}

function occupancyOf(entries: { id: string; cells: Hex[] }[]): Map<string, string[]> {
  const occupants = new Map<string, string[]>();
  for (const entry of entries) {
    for (const cell of entry.cells) {
      const key = hexKey(cell);
      const ids = occupants.get(key);
      if (ids === undefined) occupants.set(key, [entry.id]);
      else ids.push(entry.id);
    }
  }
  return occupants;
}

/**
 * Everything wrong with the layout that this module can see.
 *
 * Seam detection itself belongs to the tiling module; this function calls it
 * rather than reimplementing it, so the warning a file raises on load and the
 * warning a drop raises in the editor are the same test.
 */
export function validate(doc: LayoutDoc, catalog: Catalog): Issue[] {
  const index = partIndex(catalog);
  const panels = asArray(doc?.panels);
  const items = asArray(doc?.items);
  const issues: Issue[] = [];

  // --- unknown-part -------------------------------------------------------
  // One issue per missing partId, listing every placement that wants it. Forty
  // copies of the same missing shelf is one problem, not forty.
  const unknown = new Map<string, Set<string>>();
  const noteUnknown = (partId: string, byId: string): void => {
    const label = typeof partId === 'string' ? partId : String(partId);
    const ids = unknown.get(label);
    if (ids === undefined) unknown.set(label, new Set([byId]));
    else ids.add(byId);
  };
  const scanRefs = (id: string, partId: string): void => {
    const part = index.get(partId);
    if (part === undefined) {
      noteUnknown(partId, id);
      return;
    }
    for (const req of asArray(part.requires)) {
      if (req && !index.has(req.partId)) noteUnknown(req.partId, id);
    }
  };
  for (const panel of panels) scanRefs(panel.id, panel.partId);
  for (const item of items) scanRefs(item.id, item.partId);

  for (const partId of [...unknown.keys()].sort(byString)) {
    const ids = [...(unknown.get(partId) ?? [])].sort(byString);
    issues.push({
      level: 'error',
      code: 'unknown-part',
      message: `Part "${partId}" is not in the catalogue (referenced by ${ids.length} placement${
        ids.length === 1 ? '' : 's'
      }). It contributes nothing to the BOM.`,
      itemIds: ids,
    });
  }

  // --- panel-overlap ------------------------------------------------------
  const panelFootprints = panels.map((panel) => ({ id: panel.id, cells: panelCellsOf(panel) }));
  for (const clash of collisions(occupancyOf(panelFootprints))) {
    issues.push({
      level: 'error',
      code: 'panel-overlap',
      message: `Panels "${clash.a}" and "${clash.b}" overlap on ${clash.cells.length} cell${
        clash.cells.length === 1 ? '' : 's'
      }.`,
      itemIds: [clash.a, clash.b],
      cells: clash.cells,
    });
  }

  // --- overlap ------------------------------------------------------------
  const itemFootprints = items.map((item) => ({ id: item.id, cells: itemCells(item, catalog) }));

  // Sharing a cell is only an ERROR when both things plug INTO it — there is
  // one hexagonal hole and one insert can sit in it. Accessories bolt onto an
  // insert and stand proud of the panel, and mounting things on top of one
  // another is what the system is for, so those overlaps are advisory.
  const itemsById = new Map(items.map((i) => [i.id, i]));
  const plugsIn = (itemId: string): boolean => {
    const it = itemsById.get(itemId);
    const p = it ? catalog.parts.find((x) => x.id === it.partId) : undefined;
    return p !== undefined && (p.type === 'insert' || p.type === 'fastener');
  };

  for (const clash of collisions(occupancyOf(itemFootprints))) {
    // Only the impossible case is reported. Two accessories sharing cells is
    // ordinary — they bolt on at different depths — and reporting it would put
    // a warning on the parts list for a layout that is perfectly fine.
    if (!plugsIn(clash.a) || !plugsIn(clash.b)) continue;
    const n = clash.cells.length;
    issues.push({
      level: 'error',
      code: 'overlap',
      message:
        `Two inserts share the same hole: "${clash.a}" and "${clash.b}" ` +
        `on ${n} cell${n === 1 ? '' : 's'}.`,
      itemIds: [clash.a, clash.b],
      cells: clash.cells,
    });
  }

  // --- off-panel ----------------------------------------------------------
  // Only meaningful once there is a panel: with none, every item is trivially
  // off-panel, and the one no-panel warning below says it better than N errors.
  if (panels.length > 0) {
    const covered = new Set<string>();
    for (const panel of panelFootprints) for (const cell of panel.cells) covered.add(hexKey(cell));

    for (const footprint of itemFootprints) {
      const outside = footprint.cells.filter((c) => !covered.has(hexKey(c))).sort(byCell);
      if (outside.length === 0) continue;
      issues.push({
        level: 'error',
        code: 'off-panel',
        message: `Item "${footprint.id}" sits on ${outside.length} cell${
          outside.length === 1 ? '' : 's'
        } that no panel covers.`,
        itemIds: [footprint.id],
        cells: outside,
      });
    }
  }

  // --- crosses-seam -------------------------------------------------------
  // The editor warns about this at drop time, which covers a layout you built
  // by hand and nothing else: a layout that arrived by file, by share link, or
  // by a wall resize that moved the panels under it was never advised at all.
  // Spanning a seam is legal — some inserts exist to do it — so it stays a
  // warning, one per item.
  if (panels.length > 1) {
    for (const footprint of itemFootprints) {
      if (footprint.cells.length < 2) continue;
      if (!crossesSeam(footprint.cells, panels)) continue;
      issues.push({
        level: 'warning',
        code: 'crosses-seam',
        message: `Item "${footprint.id}" spans the join between two panels.`,
        itemIds: [footprint.id],
        cells: [...footprint.cells].sort(byCell),
      });
    }
  }

  // --- no-panel -----------------------------------------------------------
  if (panels.length === 0 && items.length > 0) {
    issues.push({
      level: 'warning',
      code: 'no-panel',
      message: `The layout has ${items.length} item${
        items.length === 1 ? '' : 's'
      } but no panels to mount them on.`,
      itemIds: items.map((item) => item.id).sort(byString),
    });
  }

  // --- no-room-for-mounts -------------------------------------------------
  // A panel hangs on the wall through its own cells: a countersunk insert drops
  // into one and takes a wall screw. Fill every cell with accessories and the
  // BOM still orders those inserts, with nowhere left to put them — a parts
  // list that is correct about what to print and silent about what cannot be
  // built. Counted per panel, because a mount has to be in the panel it holds.
  for (const panel of panels) {
    const part = index.get(panel.partId);
    if (part === undefined) continue;
    const mounts = wallMountsRequired(part, index);
    if (mounts === 0) continue;

    const cells = panelCellsOf(panel);
    const taken = new Set<string>();
    for (const footprint of itemFootprints) {
      for (const cell of footprint.cells) taken.add(hexKey(cell));
    }
    const free = cells.filter((c) => !taken.has(hexKey(c))).length;
    if (free >= mounts) continue;

    issues.push({
      level: 'warning',
      code: 'no-room-for-mounts',
      message:
        `Panel "${panel.id}" needs ${mounts} free cell${mounts === 1 ? '' : 's'} for the ` +
        `wall mounts that hold it up, and has ${free}. Clear ${mounts - free} cell` +
        `${mounts - free === 1 ? '' : 's'}, or fit the mounts before the accessories.`,
      itemIds: [panel.id],
    });
  }

  return issues;
}

/**
 * How many cells this panel's own fixings will occupy.
 *
 * Read from the panel's `requires[]` rather than recomputing the 4-plus-one-per-
 * 50-cells rule, so the count that is warned about is exactly the count that is
 * ordered — two rules would drift the moment either changed. Only requirements
 * that actually plug into a cell are counted.
 */
function wallMountsRequired(
  panel: CatalogPart,
  index: ReadonlyMap<string, CatalogPart>,
): number {
  let total = 0;
  for (const req of asArray(panel.requires)) {
    const part = req ? index.get(req.partId) : undefined;
    if (part === undefined) continue;
    if (part.type !== 'insert' && part.type !== 'fastener') continue;
    const cells = Math.max(1, asArray(part.footprint).length);
    total += countOf(req.count) * cells;
  }
  return total;
}

// ---------------------------------------------------------------------------
// BOM
// ---------------------------------------------------------------------------

/**
 * The print list.
 *
 * Always returns a usable BOM: issues are reported alongside, and anything the
 * catalogue cannot explain is left out of the numbers rather than guessed at or
 * thrown over.
 */
export function computeBom(doc: LayoutDoc, catalog: Catalog): Bom {
  const index = partIndex(catalog);
  const issues = validate(doc, catalog);

  // How many times each partId was placed on the wall (panels and items alike).
  const placements = new Map<string, number>();
  for (const panel of asArray(doc?.panels)) bump(placements, panel.partId, 1);
  for (const item of asArray(doc?.items)) bump(placements, item.partId, 1);

  // partId -> total physical count, placements plus rolled-up requirements.
  const quantities = new Map<string, number>();
  for (const [partId, times] of placements) {
    if (index.has(partId)) bump(quantities, partId, times);
  }
  for (const [partId, times] of placements) {
    const part = index.get(partId);
    if (part === undefined) continue;
    for (const req of asArray(part.requires)) {
      if (!req || !index.has(req.partId)) continue;
      const needed = countOf(req.count) * times;
      if (needed > 0) bump(quantities, req.partId, needed);
    }
  }

  // Bought hardware, from every part in the BOM — including the inserts that
  // only got there via someone else's requires[].
  const shoppingTotals = new Map<string, number>();
  for (const [partId, quantity] of quantities) {
    const part = index.get(partId);
    if (part === undefined) continue;
    for (const hw of asArray(part.hardware)) {
      if (!hw || typeof hw.item !== 'string' || hw.item.length === 0) continue;
      const needed = countOf(hw.count) * quantity;
      if (needed > 0) bump(shoppingTotals, hw.item, needed);
    }
  }

  // Lines. Unrounded running totals; rounding happens once, below.
  const printed: BomLine[] = [];
  const fasteners: BomLine[] = [];
  let totalParts = 0;
  let totalMinutes = 0;
  let totalGrams = 0;
  let totalMetres = 0;

  for (const [partId, quantity] of quantities) {
    const part = index.get(partId);
    if (part === undefined || quantity <= 0) continue;
    const est = estimateOf(part);

    totalParts += quantity;
    totalMinutes += est.minutes * quantity;
    totalGrams += est.grams * quantity;
    totalMetres += est.metres * quantity;

    const line: BomLine = {
      partId,
      name: part.name ?? partId,
      file: part.file ?? '',
      type: part.type ?? 'unknown',
      quantity,
      minutes: roundMinutes(est.minutes * quantity),
      grams: roundGrams(est.grams * quantity),
      metres: roundMetres(est.metres * quantity),
      // Per-unit figures come from the catalogue, never from total ÷ quantity:
      // that division reads back a number that has already been rounded.
      minutesEach: roundTo(est.minutes, 2),
      gramsEach: roundGrams(est.grams),
      metresEach: roundMetres(est.metres),
      supports: est.supports,
      needsReview: needsReviewOf(part),
      estimated: isEstimated(part),
    };
    (isFastener(part) ? fasteners : printed).push(line);
  }

  const byNameThenId = (a: BomLine, b: BomLine): number =>
    byString(a.name, b.name) || byString(a.partId, b.partId);
  printed.sort(byNameThenId);
  fasteners.sort(byNameThenId);

  const shopping = [...shoppingTotals.entries()]
    .map(([item, count]) => ({ item, count }))
    .sort((a, b) => byString(a.item, b.item));

  return {
    printed,
    fasteners,
    shopping,
    totals: {
      parts: totalParts,
      minutes: roundMinutes(totalMinutes),
      grams: roundGrams(totalGrams),
      metres: roundMetres(totalMetres),
      distinctParts: printed.length + fasteners.length,
    },
    issues,
  };
}
